#!/bin/sh

END=$(cut -f1 02_info_files/datatable.txt | wc -l)
#END=2

for i in $(seq 1 $END); do
  sbatch --job-name "03_collect_metrics_$i" /home/kcb95328/culaea_wgs_SNPs_copy/01_scripts/03_collect_metrics.sh "$i"
  sleep 1
done
