#!/bin/sh

END=$(cut -f1 02_info_files/datatable.txt | wc -l)
#END=39

for i in $(seq 1 $END); do
  sbatch --job-name "04_remove_duplicates_$i" /home/kcb95328/culaea_wgs_SNPs_copy/01_scripts/04_remove_duplicates.sh "$i"
  sleep 1
done
