#!/bin/sh

END=$(cut -f1 02_info_files/datatable.txt | wc -l)
#END=21

for i in $(seq 1 $END); do
  sbatch --job-name "06_gatk_realignments_$i" /home/kcb95328/culaea_wgs_SNPs_copy/01_scripts/06_gatk_realignments.sh "$i"
  sleep 1
done
